### ISSUE TITLE
Problems..

### ISSUE THREAD

**Issue by Crilum** [insomnia-creator/Termst#3]
I installed your prebuilt `crx`, so I guess that might be outdated, but I have these problems:
- The prompt doesn't stay inside the terminal:
    
![image](https://user-images.githubusercontent.com/91354257/169638061-63d5e6eb-b1bf-4c7d-a439-6e6066b2fad7.png)

- It seems that I can't type on load, I have to, like, click on the prompt a few times to get it to work... Edit: If I reload the page, I can type..

**Comment by insomnia-creator** [comment]
You have to press 'Tab' key to focus directly on the prompt. It is impossible for any extension to steal focus from the 'OmniBox' as they call it.


As for overflow issues I have already fixed it, it will be resolved within the next release.

I have not been able to get much time to do work on Termst this week, maybe next week onwards I'll work more on it.

By the way: you can access the 'latest' tree of Termst with the newest features from the website [termst.vercel.app](http://termst.vercel.app/)

Cheers 🎉.

**Comment by Crilum** [comment]
Thanks. I'll close this (or you can) whenever your next release is!

**Comment by insomnia-creator** [comment]
Fixed in latest release
